#!/usr/bin/env zsh
set -euo pipefail
setopt nocaseglob

if [[ ${#@} -gt 0 ]]; then
	files=("$@")
else
	extensions=(${(f)"$(globs images -x avif)"})
	files=()
	for ext in "${extensions[@]}"; do
		files+=(${~ext}(N))
	done
fi

if [[ ${#files[@]} -eq 0 ]]; then
	echo "No image files found." >&2
	exit 1
fi

img2avif "${files[@]}"
