#!/usr/bin/env zsh

mkdir -p original
setopt localoptions nocaseglob

extensions=(
    "*.jpeg" "*.jpg" "*.png"
    "*.arw" "*.dng" "*.psd" "*.jxl"
)

find . -maxdepth 1 -type f \( \
    $(printf -- "-iname %s -o " "${extensions[@]}") \
    -false \) -print0 | \
    parallel -0 -j "$(sysctl -n hw.ncpu)" '
        heic {}
        mv {} original/{}
    '