#!/usr/bin/env zsh
setopt localoptions nocaseglob

extensions=(${(f)"$(globs videos)"})

find . -maxdepth 1 -type f \( \
    $(printf -- "-iname %s -o " "${extensions[@]}" | sed 's/ -o $//') \
    \) -print0 | \
    parallel --bar -0 -j "$(sysctl -n hw.ncpu)" vprev "{}"
