#!/usr/bin/env zsh
xlf=$1
shift

if [[ $# -gt 0 ]]; then
	echo "» $xlf"
	xlsx2csv $xlf $xlf:t:r -s 0 "$@"
else
	for xl in *.xlsx; do
		echo "» xl"
		xlsx2csv $xl $xl:t:r -s 0
		echo "Converted $xl to csvs in folder $xl:t:r"
		trash $xl
	done
fi